# Basic Matrix Operations

### Matrix Addition

Let $A=[a_{ij}]$ and $B=[b_{ij}]$ be two matrices of dimensions $m \times n$. Then the sum of matrices $A$ and $B$ is the matrix $C=[c_{ij}]$ of dimensions $m \times n$, where $c_{ij}=a_{ij}+b_{ij}$.

### Matrix Scalar Multiplication

Let $A=[a_{ij}]$ be a matrix of dimensions $m \times n$, and let $k$ be a scalar. Then the product of matrix $A$ and scalar $k$ is the matrix $B=[b_{ij}]$ of dimensions $m \times n$, where $b_{ij}=k \cdot a_{ij}$.

### Matrix Multiplication

Let $A=[a_{ij}]$ be a matrix of dimensions $m \times n$, and $B=[b_{ij}]$ be a matrix of dimensions $n \times p$. Then the product of matrices $A$ and $B$ is the matrix $C=[c_{ij}]$ of dimensions $m \times p$, where $c_{ij}=\sum_{k=1}^{n} a_{ik} \cdot b_{kj}$.


### Example 1

Let $A=\begin{bmatrix} 1 & 2 \\ 3 & 4 \end{bmatrix}$ and $B=\begin{bmatrix} 5 & 6 \\ 7 & 8 \end{bmatrix}$.
Then the sum of matrices $A$ and $B$ is

$$
C=
A+B=\begin{bmatrix} 1+5 & 2+6 \\ 3+7 & 4+8 \end{bmatrix}=\begin{bmatrix} 6 & 8 \\ 10 & 12 \end{bmatrix}.
$$

### Example 2

Let $A=\begin{bmatrix} 1 & 2 \\ 3 & 4 \end{bmatrix}$ and $k=2$.

Then the product of matrix $A$ and scalar $k$ is

$$
B=
k \cdot A=2 \cdot \begin{bmatrix} 1 & 2 \\ 3 & 4 \end{bmatrix}=\begin{bmatrix} 2*1 & 2*2 \\ 2*3 & 2*4 \end{bmatrix}=\begin{bmatrix} 2 & 4 \\ 6 & 8 \end{bmatrix}.
$$

### Example 3

Let
$A=\begin{bmatrix} 1 & 2 \\ 3 & 4 \end{bmatrix}$
and
$B=\begin{bmatrix} 5 & 6 \\ 7 & 8 \end{bmatrix}$.

Then the product of matrices $A$ and $B$ is

$$
C=
A \cdot B=\begin{bmatrix} 1*5+2*7 & 1*6+2*8 \\ 3*5+4*7 & 3*6+4*8 \end{bmatrix}=\begin{bmatrix} 19 & 22 \\ 43 & 50 \end{bmatrix}.
$$

In [ ]:
# Example 1: Matrix addition in sympy
import sympy as sp

A=sp.Matrix([[1,2],[3,4]])
B=sp.Matrix([[5,6],[7,8]])
A # display matrix A

In [ ]:
B # display matrix B

In [ ]:
sp.Matrix([[6,8],[10,12]])==A+B # verify matrix addition

In [ ]:
# Example 2: Scalar multiplication
A=sp.Matrix([[1,2],[3,4]]) # define matrix A

sp.Matrix([[2,4],[6,8]])==2*A # verify scalar multiplication

In [ ]:
# Example 3: Multiplication of two matrices

A=sp.Matrix([[1,2],[3,4]]) # define matrix A
B=sp.Matrix([[5,6],[7,8]]) # define matrix B

sp.Matrix([[19,22],[43,50]])==A*B # verify matrix multiplication

### Necessary Condition for Matrix Multiplication

Remember that matrices can have different numbers of rows and columns.

To multiply two matrices $A_{m \times n}$ and $B_{n \times k}$, where $A$ has dimensions $m \times n$ and $B$ has dimensions $n \times k$, the number of columns of matrix $A$ must equal the number of rows of matrix $B$. Otherwise, matrix multiplication is not possible.

$$
A_{m \times n} \cdot B_{n \times k} = C_{m \times k}
$$

For example, if $A_{3 \times 3}$ and $B_{3 \times 3}$, then the resulting matrix $C_{3 \times 3}$.

<img src="https://www.mscroggs.co.uk/img/full/multiply_matrices.gif" alt="Matrix Multiplication GIF" width="400">

### Matrix Multiplication is Not Commutative

Matrix multiplication is not commutative, i.e., in general $A \cdot B \neq B \cdot A$.

In [ ]:
# Example of multiplying rectangular matrices
import sympy as sp
A=sp.Matrix([[1,2],[3,4],[5,6]]) # define matrix A_{3 x 2}
B=sp.Matrix([[1,2,3],[4,5,6]]) # define matrix B_{2 x 3}
C=sp.Matrix([[9,12,15],[19,26,33],[29,40,51]]) # define matrix C_{3 x 3}

A*B # multiply matrices A and B to get a 3x3 matrix

In [ ]:
B*A # multiply matrices B and A to get a 2x2 matrix

In [ ]:
B*C # multiply matrices B and C to get a 2x3 matrix

---
## Exercises for Students

1. Calculate the sum of matrices $A=\begin{bmatrix} 1 & 2 \\ 3 & 4 \end{bmatrix}$ and $B=\begin{bmatrix} 5 & 6 \\ 7 & 8 \end{bmatrix}$.

2. Calculate the product of matrix $A=\begin{bmatrix} 4 & 2 \\ 12 & 4 \end{bmatrix}$ and scalar $k=\frac{1}{4}$.

3. Calculate the products $A\cdot B$ and $B \cdot A$ for matrices $A=\begin{bmatrix} 3 & 2 \\ 2 & 4 \end{bmatrix}$ and $B=\begin{bmatrix} 4 & 1 \\ 6 & 4 \end{bmatrix}$.

In [2]:
import numpy as np

# 1. Question: Matrix Addition
A1 = np.array([[1, 2], [3, 4]])
B1 = np.array([[5, 6], [7, 8]])
sum_question1 = A1 + B1
print("1st Question: A + B =\n", sum_question1)

# 2. Question: Matrix Multiplication by Scalar
A2 = np.array([[4, 2], [12, 4]])
k = 1/4
scalar_multiplication_question2 = k * A2
print("2nd Question: k * A =\n", scalar_multiplication_question2)

# 3. Question: Matrix Multiplications (A·B and B·A)
A3 = np.array([[3, 2], [2, 4]])
B3 = np.array([[4, 1], [6, 4]])

product_AB_question3 = np.dot(A3, B3)
product_BA_question3 = np.dot(B3, A3)

print("3rd Question: A · B =\n", product_AB_question3)
print("3rd Question: B · A =\n", product_BA_question3)


1st Question: A + B =
 [[ 6  8]
 [10 12]]
2nd Question: k * A =
 [[1.  0.5]
 [3.  1. ]]
3rd Question: A · B =
 [[24 11]
 [32 18]]
3rd Question: B · A =
 [[14 12]
 [26 28]]
